language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
services:
  - postgresql
before_install: gem install bundler -v 1.12.5
before_script:
  - cp config/database.yml.sample config/database.yml && rake db:test:setup
script: bundle exec rspec
